### ISSUE TITLE
new build with later svelte

### ISSUE THREAD

**Issue by janl** [pateketrueke/yrv#8]
I’m using this with snowpack and ran into the error pasted below.

I traced this to having svelte version ^3.4.4 hardcoded in the devDependencies. When updated to latest 3.17.3 and rebuilding, the snowpack import works fine.

I didn’t have time to bisect this to find out which version of svelte broke this.

```
- snowpack installing... 
Error: 'on_outro' is not exported by node_modules/svelte/internal/index.mjs
    at error (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:5330:30)
    at Module.error (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:9733:16)
    at handleMissingExport (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:9634:28)
    at Module.traceVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:10072:24)
    at ModuleScope.findVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:8679:39)
    at FunctionScope.findVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:3015:38)
    at ChildScope.findVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:3015:38)
    at FunctionScope.findVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:3015:38)
    at ChildScope.findVariable (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:3015:38)
    at Identifier$1.bind (/Users/jan/Work/timeliner/node_modules/rollup/dist/rollup.js:4353:40)
```

**Comment by pateketrueke** [comment]
I though it was a easy thing, but upgrading to latest svelte actually broke a single test, I need time to figure out what happened.

So much thanks for your feedback!
